name: aoc_2024
description: Advent of Code 2024 solutions in Dart
version: 1.0.0
repository: https://github.com/dancarroll/aoc_2024

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  collection: ^1.19.1
  quiver: ^3.2.2
  clique: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^6.0.0
  test: ^1.26.2
