name: aoc_2025
description: Advent of Code 2025 solutions in Dart
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  collection: ^1.19.1
  quiver: ^3.2.2
  clique: ^1.0.2

  aoc_shared:
    path: ../aoc_shared

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^6.0.0
  test: ^1.28.0
